# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='snippet',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Snippet'),
        ),
        migrations.AddField(
            model_name='event',
            name='snippet',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Snippet'),
        ),
        migrations.AddField(
            model_name='eventrule',
            name='snippet',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='perspective',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='relativeposition',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
