# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-16 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper_base', '0002_auto_20170116_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='raw_text',
            field=models.TextField(verbose_name='Raw Text'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timekeeper_base.Action'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timekeeper_base.EventRule'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timekeeper_base.RelativePosition'),
        ),
        migrations.AlterField(
            model_name='event',
            name='raw_text',
            field=models.TextField(verbose_name='Raw Text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='raw_text',
            field=models.TextField(verbose_name='Raw Text'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
