# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-16 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeper_base', '0003_auto_20170116_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timekeeper_base.Element')),
                ('type', models.CharField(default='interaction', max_length=25, verbose_name='Set Type')),
                ('method', models.CharField(default='I', help_text='Union or Intersection', max_length=1, verbose_name='Set Method')),
                ('actors', models.ManyToManyField(related_name='parent_products', to='timekeeper_base.Actor')),
            ],
            options={
                'verbose_name': 'Set',
                'ordering': ['-created'],
                'verbose_name_plural': 'Sets',
            },
            bases=('timekeeper_base.element',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='element_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='alias',
            name='actor',
        ),
        migrations.AddField(
            model_name='alias',
            name='element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timekeeper_base.Element'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alias',
            name='type',
            field=models.CharField(default='', max_length=25, verbose_name='Alias Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='perspectives',
            field=models.ManyToManyField(to='timekeeper_base.Perspective'),
        ),
        migrations.AlterField(
            model_name='timekeeper',
            name='timeline',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='timekeeper_base.Timeline'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
